name: Check README

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  check_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check README
      run: |
        if grep -q 'John Doe' README.md; then
          echo "Readme check passed!"
        else
          echo "Error: README.md does not contain the required name."
          exit 1
        fi

